server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://prometheus-loki.domain.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        env: production
        host: prometheus-fra-0
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
